name: deploy-uptime-kuma

on:
  push:
    paths:
      - '.github/workflows/uptime-kuma.yml'
      - 'uptime-kuma/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: uptime-kuma
      url: https://status.aosus.org
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@2b498977f3e4dae1a5c7da1f138a9e6163220d65
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_SECRET }}
          tags: tag:deploy-ci
          hostname: Github-actions
          version: ${{ vars.TAILSCALE_VERSION }}

      - name: Start Deployment
        uses: FarisZR/docker-compose-gitops-action@v1
        with:
          remote_docker_host: ${{ secrets.server_address }}
          tailscale_ssh: true # no need for manual private and public keys
          compose_file_path: uptime-kuma/docker-compose.yml
          args: -p uptime-kuma up -d --remove-orphans